### ISSUE TITLE
[ToDo list] Organisation profile

### ISSUE THREAD

**Issue by naskio** [G-Research/.github#2]
Here is a todo list for improving the GitHub organisation profile:

---
1. [x] Update organisation avatar to

![v1](https://github.com/G-Research/brand/raw/main/avatar/avatar-transparent.png)

---
1. [x] Update organisation description to
```
CREATE TODAY. PREDICT TOMORROW.
```

---
1. [x] Set address to
```
London + Dallas
```

---
1. [x] Update organisation email to
```
admin@gr-oss.io
```

---
1. [x] Add some relevant social links from this list
```
https://www.gresearch.com
https://opensource.gresearch.com
```

**Comment by stackedsax** [comment]
On that avatar, can we please make the white background transparent?  I think I did this years ago but somehow it got reverted.  It makes us look terrible for anyone with dark mode on.

The address is only a single dropdown so I can't select Dallas as well.  I'll leave it as London.

**Comment by naskio** [comment]
Hi @stackedsax 
- [avatar](https://github.com/G-Research/brand/blob/main/avatar/avatar-transparent.png) has been updated:
  - Using a transparent background
  - Tested compatibility on both light and dark modes
- Regarding the address, I found a similar implementation on the [Hugging Face GitHub profile](https://github.com/huggingface). To achieve that:
  1. Right-click the address input field
  2. Select "Inspect" to open developer tools
  3. Modify the input value to `London + Dallas`
  4. Click "Update profile" to save changes
- I would also like to suggest the removal of this link `https://www.gresearch.co.uk/` (we already have the .com alternative)

**Comment by jgiannuzzi** [comment]
* I used the GitHub API to update the location (the address hack above didn't work)
* I updated the avatar
* I removed the .co.uk link

**Comment by jgiannuzzi** [comment]
I believe this is all done now. @c-rindi @naskio could you please confirm?

**Comment by naskio** [comment]
@jgiannuzzi
Yes, LGTM 👌
Thanks
